version: '1.1.1-{branch}.{build}'

pull_requests:
  do_not_increment_build_number: true

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.1.1'
  assembly_file_version: '1.1.1'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: Pretzel.MultipartPost\bin\$(configuration)\Pretzel.MultipartPost.dll
  name: Pretzel.MultipartPost.dll